db.restaurants.find()
db.restaurants.find({}, { _id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({}, { _id: 0, name: 1, borough: 1, cuisine: 1 })
db.restaurant.find({}, { _id: 0, restaurant_id: 1, name: 1, borough: 1, 'address.zipcode': 1 })
db.restaurants.find({ borough: "Bronx" })
db.restaurants.find({ borough: "Bronx" }).limit(5)
db.restaurants.find({ borough: "Bronx" }).skip(5).limit(5)
db.restaurants.find({ grades: { $elemMatch: { score: { $gt: 90 } } } })
db.restaurants.find({ grades: { $elemMatch: { $and: [{ score: { $gt: 80 } }, { score: { $lt: 100 } }] } } })
db.restaurants.find({ "address.coord.0": { $lt: -95.754168 } })
db.restaurants.find({ $and: [{ "cuisine": { $ne: "American " } }, { grades: { $elemMatch: { score: { $gt: 90 } } } }, { "address.coord.1": { $lt: -65.754168 } }] })
db.restaurants.find({ "cuisine": { $ne: "American " }, grades: { $elemMatch: { score: { $gt: 70 } } }, "address.coord.0": { $lt: -65.754168 } })
db.restaurants.find({ $and: [{ "cuisine": { $ne: "American " } }, { grades: { $elemMatch: { "grade": "A" } } }, { "borough": { $ne: "Brooklyn" } }] }).sort({ cuisine: -1 });
db.restaurants.find({ name: { $regex: /^Wil/ } }, { _id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({ name: { $regex: /ces$/ } }, { _id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({ name: { $regex: /Reg/ } }, { _id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({ $and: [{ borough: "Bronx" }, { $or: [{ cuisine: "Chinese" }, { cuisine: "American " }] }] })
db.restaurants.find({ $or: [{ borough: "Staten Island" }, { borough: "Queens" }, { borough: "Bronx" }, { borough: "Brooklyn" }] }, { _id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({ $nor: [{ borough: "Staten Island" }, { borough: "Queens" }, { borough: "Bronx" }, { borough: "Brooklyn" }] }, { _id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({ grades: { $elemMatch: { score: { $lt: 10 } } } }, { _id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({ $and: [{ cuisine: /seafood/i }, { name: { $not: /^Wil/ } }, { cuisine: { $not: /American/ } }, { cuisine: { $not: /Chinese/ } }] }, { _id: 1, name: 1, borough: 1, cuisine: 1 })
db.restaurants.find({ $and: [{ grades: { $elemMatch: { grade: "A" } } }, { "grades.score": 11 }, { "grades.date": new Date("2014-08-11T00:00:00Z") }] }, { _id: 1, name: 1, "grades.grade": 1 })
db.restaurants.find({ $and: [{ "grades.1.grade": "A" }, { "grades.1.score": 9 }, { "grades.1.date": new Date("2014-08-11T00:00:00Z") }] }, { _id: 1, name: 1, grades: 1 })
db.restaurants.find({ "address.coord.1": { $gt: 42, $lt: 52 } }, { _id: 1, name: 1, "address.street": 1, "address.coord": 1 })
db.restaurants.find().sort({ name: 1 })
db.restaurants.find().sort({ name: -1 })
db.restaurants.find().sort({ cuisine: 1 }, { borough: -1 })
db.restaurants.find({ "address.street": { $exists: true } })
db.restaurants.find({ "address.coord": { $type: "double" } })
db.restaurants.find({ "grades.score": { $mod: [7, 0] } }, { _id: 1, name: 1, grades: { grade: 1 }, grades: { score: 1 } })
db.restaurants.find({ name: { $regex: /mon/ } }, { _id: 0, name: 1, borough: 1, "address.coord": 1, cuisine: 1 })
db.restaurants.find({ name: { $regex: /^Mad/ } }, { _id: 0, name: 1, borough: 1, "address.coord": 1, cuisine: 1 })